# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from password2 import Ui_Form 
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(763, 575)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.title1 = QtWidgets.QLabel(self.centralwidget)
        self.title1.setGeometry(QtCore.QRect(50, 0, 191, 141))
        self.title1.setObjectName("labei_1")

        self.title2 = QtWidgets.QLabel(self.centralwidget)
        self.title2.setGeometry(QtCore.QRect(70, 100, 151, 41))
        self.title2.setObjectName("label_2")

        self.button_next = QtWidgets.QPushButton(self.centralwidget)
        self.button_next.setGeometry(QtCore.QRect(570, 500, 75, 23))
        self.button_next.setObjectName("pushButton")

        self.pushButton_quit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_quit.setGeometry(QtCore.QRect(660, 500, 75, 23))
        self.pushButton_quit.setObjectName("pushButton_2")

        self.graph1 = QtWidgets.QLabel(self.centralwidget)
        self.graph1.setGeometry(QtCore.QRect(280, -120, 481, 421))
        self.graph1.setTextFormat(QtCore.Qt.RichText)
        self.graph1.setObjectName("label_3")

        self.graph2 = QtWidgets.QLabel(self.centralwidget)
        self.graph2.setGeometry(QtCore.QRect(50, 180, 681, 321))
        self.graph2.setTextFormat(QtCore.Qt.RichText)
        self.graph2.setObjectName("label_4")

        self.text = QtWidgets.QLabel(self.centralwidget)
        self.text.setGeometry(QtCore.QRect(50, 160, 621, 16))
        self.text.setObjectName("label_5")

        self.title1.raise_()
        self.title2.raise_()
        self.pushButton_quit.raise_()
        self.button_next.raise_()
        self.graph1.raise_()
        self.graph2.raise_()
        self.text.raise_()

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 763, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_quit.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.button_next.clicked.connect(self.secondscr)
        self.button_next.clicked.connect(MainWindow.close)

    def secondscr(self):
             self.Form = QtWidgets.QWidget()
             self.ui = Ui_Form()
             self.ui.setupUi(self.Form)
             self.Form.show() 

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title1.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Smart Helmet Reciever</span></p></body></html>"))
        self.title2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#0000ff;\">Click \'Next\' to continue!</span></p></body></html>"))
        self.button_next.setText(_translate("MainWindow", "Next"))
        self.pushButton_quit.setText(_translate("MainWindow", "Quit"))
        self.graph1.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/newPrefix/images.jpg\"/></p></body></html>"))
        self.graph2.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/newPrefix/part-00156-4304.jpg\"/></p></body></html>"))
        self.text.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ff0000;\">This is a program linked with smart helmet to plot graphs of impacts. The system is developed by Group M.</span></p></body></html>"))
import ref


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
