# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from third2 import Ui_Form as Login
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(401, 410)

        self.textbox_password = QtWidgets.QLineEdit(Form)
        self.textbox_password.setGeometry(QtCore.QRect(160, 320, 131, 20))
        self.textbox_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.textbox_password.setObjectName("lineEdit_2")

        self.password_text = QtWidgets.QLabel(Form)
        self.password_text.setGeometry(QtCore.QRect(100, 320, 51, 21))
        self.password_text.setObjectName("label_2")

        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(160, 290, 131, 20))
        self.lineEdit.setObjectName("lineEdit")

        self.loginbutton = QtWidgets.QPushButton(Form)
        self.loginbutton.setGeometry(QtCore.QRect(310, 370, 75, 23))
        self.loginbutton.setObjectName("pushButton")
        self.loginbutton.clicked.connect(self.check_password)
        self.loginbutton.clicked.connect(Form.close)

        self.username_text = QtWidgets.QLabel(Form)
        self.username_text.setGeometry(QtCore.QRect(100, 280, 71, 31))
        self.username_text.setObjectName("label")

        self.graph = QtWidgets.QLabel(Form)
        self.graph.setGeometry(QtCore.QRect(-150, -170, 651, 451))
        self.graph.setObjectName("label_3")

        self.warning_text = QtWidgets.QLabel(Form)
        self.warning_text.setGeometry(QtCore.QRect(10, 350, 381, 20))
        self.warning_text.setObjectName("label_4")

        self.title_text = QtWidgets.QLabel(Form)
        self.title_text.setGeometry(QtCore.QRect(140, 260, 121, 21))
        self.title_text.setObjectName("label_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.password_text.setText(_translate("Form", "Password:"))
        self.loginbutton.setText(_translate("Form", "Log in"))
        self.username_text.setText(_translate("Form", "Username:"))
        self.graph.setText(_translate("Form", "<html><head/><body><p><img src=\":/newPrefix/2021-11-21 (2).png\"/></p></body></html>"))
        self.warning_text.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; color:#ff0000;\">*Please make sure correct password and username are used! </span></p></body></html>"))
        self.title_text.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600; color:#0000ff;\">Smart Helmet Log in</span></p></body></html>"))

    def thirdscr(self):
        self.Form = QtWidgets.QWidget()
        self.ui = Ui_Form1()
        self.ui.setupUi(self.Form)
        self.Form.show()
    
    def check_password(self):
        if self.lineEdit.text() == 'bbb' and self.textbox_password.text() == '000':
            #self.pushButton.clicked.connect(self.thirdscr)
            self.thirdscr()
        else:
            msg = QtWidgets.QMessageBox()
            msg.setText('Incorrect Password')
            msg.exec_()



import ref


if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        Form = QtWidgets.QWidget()
        ui = Ui_Form()
        ui.setupUi(Form)
        Form.show()
        sys.exit(app.exec_())
